apiVersion: v1
kind: Namespace
metadata:
  name: forbidden-namespace
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: forbidden-namespace
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  values:
    replicaCount: 1
