apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: capsule
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/capsule
  prune: true
  wait: true
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: capsule-proxy
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: capsule
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/capsule-proxy
  prune: true
  wait: true
  timeout: 10m
